// <auto-generated />
using System;
using InstaBot.Service.DataBaseModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace InstaBot.Service.Migrations
{
    [DbContext(typeof(InstaBotContext))]
    [Migration("20180829133201_init3")]
    partial class init3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("InstaBot.Service.DataBaseModels.Queue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DelayInSeconds");

                    b.Property<bool>("IsActive");

                    b.Property<DateTime>("LastActivity");

                    b.Property<string>("LoadId");

                    b.Property<int>("QueueState");

                    b.Property<int>("QueueType");

                    b.Property<int>("LoginDataId");

                    b.HasKey("Id");

                    b.HasIndex("LoginDataId");

                    b.ToTable("Queues");
                });

            modelBuilder.Entity("InstaBot.Service.DataBaseModels.LoginData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<string>("Password");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("InstaBot.Service.DataBaseModels.UserActivityHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("PostedImageURI");

                    b.Property<int>("QueueId");

                    b.HasKey("Id");

                    b.HasIndex("QueueId");

                    b.ToTable("UserActivityHistories");
                });

            modelBuilder.Entity("InstaBot.Service.DataBaseModels.Queue", b =>
                {
                    b.HasOne("InstaBot.Service.DataBaseModels.LoginData", "LoginData")
                        .WithMany()
                        .HasForeignKey("LoginDataId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("InstaBot.Service.DataBaseModels.UserActivityHistory", b =>
                {
                    b.HasOne("InstaBot.Service.DataBaseModels.Queue", "Queue")
                        .WithMany()
                        .HasForeignKey("QueueId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
